services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_mail:app
    envVars:
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USERNAME
        value: habiballahportfolioweb@gmail.com
      - key: MAIL_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        value: habiballahportfolioweb@gmail.com